In [82]:
from sklearn.datasets import load_wine
import pandas as pd 


# extraindo o data set da biblioteca sk learn
vinhos_dataset = load_wine()
df = pd.DataFrame(data=vinhos_dataset.data, columns=vinhos_dataset.feature_names)
df['classe'] = vinhos_dataset.target # adicioando a coluna de alvos ou classes 
df

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     od280/od315_of_diluted_wines  proline  classe  
0                            3.92   1065.0       0  
1                            3.40   1050.0       0  
2                            3.17   1185.0       0  
3                            3.45   1480.0       0  
4                            2.93    735.0       0  
..                            ...      ...     ...  
173                          1.74    740.0       2  
174                          1.56    750.0       2  
175                          1.56    835.0       2  
176                          1.62    840.0       2  
177                          1.60    560.0       2  

[178 rows x 14 columns]

In [83]:
# criando os previsores e as classes 
previsores = df.iloc[:, 0:13].values # caracteristicas 
classe = df.iloc[:, 13].values # classe do vinho (0, 1 ou 2)

In [84]:
from sklearn.model_selection import train_test_split
# criando base de dados de treinamento e teste (25% da base para testar)
previsores_treinamento, previsores_teste, classe_treinamento, classe_teste = train_test_split(previsores, classe, test_size=0.25)

In [85]:
# realizando o preprocessamento do dados 
from sklearn.preprocessing import StandardScaler
from keras.utils import to_categorical

# Normalizar os dados
scaler = StandardScaler()
previsores_treinamento = scaler.fit_transform(previsores_treinamento)
previsores_teste = scaler.transform(previsores_teste)

# Convertendo as classes para que as classes cotenham uma sequencia de 0's e 1 (assim como no exemplo das iris), one hot encoder
# 100
# 010
# 001
classe_treinamento = to_categorical(classe_treinamento)
classe_teste = to_categorical(classe_teste)

In [87]:
from keras.models import Sequential
from keras.layers import Dense
# construindo a rede 
classificador = Sequential()
classificador.add(Dense(units = 13, activation = 'relu', input_dim = 13)) # primeira camada oculta
classificador.add(Dense(units = 13, activation = 'relu')) # segunda camada oculta
classificador.add(Dense(units = 3, activation = 'softmax')) # camada de saida
# compilando a rede 
classificador.compile(optimizer = 'adam', loss = 'categorical_crossentropy', 
                      metrics = ['categorical_accuracy'])

In [88]:
# treinando a rede 
classificador.fit(previsores_treinamento, classe_treinamento, batch_size = 10, 
                  epochs = 100)

Epoch 1/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - categorical_accuracy: 0.4708 - loss: 1.0255   
Epoch 2/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 0.5220 - loss: 0.9444 
Epoch 3/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - categorical_accuracy: 0.6938 - loss: 0.8328 
Epoch 4/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 0.7265 - loss: 0.8035 
Epoch 5/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 0.8482 - loss: 0.6863 
Epoch 6/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 0.8604 - loss: 0.6685 
Epoch 7/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 0.8952 - loss: 0.5683 
Epoch 8/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 0.9179 - loss: 0.5330 
Epoch 9/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 0.9249 - loss: 0.4444 
Epoch 10/100
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 0.8968 - loss: 0.4159 
Epoch 11/100
14/1

In [89]:
# avaliando os resultados da rede pelo keras
resultado = classificador.evaluate(previsores_teste, classe_teste)
resultado

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - categorical_accuracy: 0.9852 - loss: 0.0249 


[0.030266860499978065, 0.9777777791023254]

In [93]:
import numpy as np 
previsoes = classificador.predict(previsores_teste) # fazendo o teste sem ser pelo keras
previsoes = (previsoes>0.5)# valor true e false
print(f"previsoes: {previsoes}") # exibindo com valoes true e false 

# convertendo o dados para criar a matriz de confusão 
classe_teste2 = [np.argmax(t) for t in classe_teste]
previsoes2 = [np.argmax(t) for t in previsoes]

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step 
previsoes: [[False  True False]
 [False  True False]
 [False False  True]
 [False  True False]
 [False  True False]
 [False  True False]
 [ True False False]
 [False  True False]
 [False  True False]
 [False  True False]
 [False False  True]
 [False False  True]
 [False  True False]
 [False False  True]
 [ True False False]
 [ True False False]
 [False False  True]
 [False False  True]
 [ True False False]
 [False False  True]
 [False  True False]
 [ True False False]
 [ True False False]
 [False False  True]
 [False False  True]
 [False False  True]
 [ True False False]
 [False False  True]
 [False  True False]
 [ True False False]
 [False False  True]
 [False  True False]
 [ True False False]
 [False False  True]
 [False  True False]
 [ True False False]
 [False False  True]
 [False  True False]
 [False  True False]
 [ True False False]
 [ True False False]
 [False  True False]
 [ True False False]
 [False  True False]
 [False False  True]]


In [95]:
# contruindo a matriz de confusao para avaliar os erros e acertos da rede da rede 
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(previsoes2, classe_teste2)
print(f"Matriz de confusão\n{matriz}")

Matriz de confusão
[[13  0  0]
 [ 0 16  1]
 [ 0  0 15]]
