Este arquivo contem todos os codigos vistos no card 4 e comentarios pessoais dos mesmos!

Card 4 tem por objetivo aprender duas bibliotecas de de python para data science e machine learning: 
**Numpy** e **Pandas**

# Biblioteca numpy 

é uma biblioteca de álgebra linear para python extremamente rapida, uma vez que seu principais metodos foram compilados em C

In [12]:
import numpy as np

In [3]:
minha_lista = [1,2,3]
minha_lista

np.array(minha_lista)

array([1, 2, 3])

In [4]:
minha_matriz = [[1,2,3],[4,5,6],[7,8,9]]
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
#cria um vetor de 0 a 9
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
#cria um vetor de 0 a 9 pulando de 2 em 2
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [8]:
#Vetor de zeros
arr = np.zeros(3)
arr

array([0., 0., 0.])

In [10]:
#Matriz de 0's
arr = np.zeros((5,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
#matriz de 1's
arr = np.ones((5,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
#matriz identidade
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
#Vai eixibir N numeros (n=2) igual mente espaçados dentro da serie ( no caso vai exibir 0 e 10)
np.linspace(0,10,2)

array([ 0., 10.])

In [18]:
#Sorteia N numeros (distribuição uniforme)
np.random.rand(5)


array([0.56206445, 0.07667343, 0.85228831, 0.75667539, 0.29114668])

In [17]:
#Sorteia numeros  (Distribuição normal)
np.random.randn(5)

array([-1.07941574,  0.0679575 ,  1.33579903, -0.88277932, -0.50737898])

In [19]:
#Sorteia numeros inteiros dentro de um intervalo (o a 99)
np.random.randint(0,100,10)

array([60, 18, 27, 78, 18, 32, 85, 38, 80, 85])

In [21]:
arr = np.random.rand(25)
#Tranforma o array em uma matriz 
arr.reshape((5,5))

array([[0.72234379, 0.59378909, 0.62207078, 0.88652403, 0.6365755 ],
       [0.66679841, 0.19814154, 0.43648384, 0.16573237, 0.00100407],
       [0.36653049, 0.79070726, 0.18491218, 0.19201502, 0.53403978],
       [0.44620221, 0.32036459, 0.06690853, 0.10161999, 0.77016261],
       [0.26964613, 0.19729457, 0.50996266, 0.93735167, 0.0312996 ]])

In [23]:
#Pega o maior valor de arr
arr.max()

0.9373516717018016

In [24]:
#Pega o maior valor de arr
arr.min()

0.0010040716758151769

In [25]:
#Indice do maior valor de arr 
arr.argmax()

23

In [28]:
#Indice do menor valor de arr 
arr.argmin()

9

In [31]:
array = np.arange(0,30,3)
array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [32]:
#elemento da pos 3 
array[3]

9

In [33]:
#elemento da pos 2 a 4 (se nao tiver nada no lugar do 2 começa da pos 0, 
#analogamente se nao tiver nada no lugar do 5 pega do primeiro valor de posição ( no caso 2) ate o final )
array[2:5]

array([ 6,  9, 12])

In [35]:
#a partir do indice 2 ate o final recebe o valor 100
array[2:] = 100
array


array([  0,   3, 100, 100, 100, 100, 100, 100, 100, 100])

In [37]:
array = np.arange(50).reshape((5,10))
array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [39]:
#primeiro colchete Linhas e segundo refere-se as colunas
#vai pegar as linhas ate a linha de indice 3
array[:3][:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [42]:
array2 = array[:3]
array2[:] = 100
#vai alterar tanto o array2 quanto o array original
#pois o array 2 vai apontar pro array original
array

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

In [47]:
#Agora realmente copia o array original
array2 = array[:3].copy()
array2[:] = 200
array


array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

In [48]:
#antes da virgula refere se as linhas e apos a virgula as colunas
#linhas de 1 a 3 e coluna de 5 em diante  
array[1:4,5:]

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [ 35,  36,  37,  38,  39]])

In [51]:
# Matriz de verdadeiros e falsos (verdadeiro onde é maior que 50)
array > 50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [52]:
array = np.arange(0,16)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [53]:
#soma 2 arrays de mesmo tamanho
array + array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [54]:
#subtrai 2 arrays de mesmo tamanho
array - array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [55]:
#multiplica 2 arrays de mesmo tamanho
array * array

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225])

In [57]:
#eleva o array ao quadrado 
array**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225])

In [58]:
#soma, subtração e multiplação de arrays por escalares
array + 100
array - 100
array * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000,
       1100, 1200, 1300, 1400, 1500])

In [59]:
#raiz quadrada elemento a elemento de um array 
np.sqrt(array)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335])

In [60]:
#exponenciação de um array 
np.exp(array)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06])

In [61]:
#media de um array 
np.mean(array)

7.5

In [62]:
#desvio padrao de um array
np.std(array)

4.6097722286464435

In [64]:
#seno dos elementos do vetor 
np.sin(array)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784])

In [66]:
#valor maximo do vetor de dois metodos
np.max(array)
array.max()

15

In [67]:
#valor minimo do vetor
np.min(array)
array.min()

0

**Exercícios sobre Numpy**

In [ ]:
# 1) crie uma mtriz de 10 zeros
np.zeros(10)

# 2) crie uma matriz de 10 ones
np.ones(10)

# 3) crie uma matriz de 10 cincos
np.ones(10)*5

# 4) crie um array de inteiros de 100 até 50 
np.arange(10,51)

# 5) crie um array de numeros pares de 10 ate 50 
np.arange(10,51,2)

# 6) crie uma matriz 3x3 com valores de 0 a 8
np.arange(0,9).reshape(3,3)

# 7) crie uma matriz identidade de 3x3
np.eye(3)

# 8) use numpy par gerar numeros aleatorios entre 0 e 1
np.random.rand(1)

# 9) use numpy para gerar um array de 25 numeros aleatorios tirados e uma distribuição normal
np.random.randn(25)

# 10) 
np.arange(0,101)/100

# 11) crie um array de tamanho 20 igualmente espaçado entre o e 1 
np.linspace(0,1,20)


In [ ]:
'''Indexação Numpy e seleção'''
mat = np.arange(1,26).reshape(5,5)

# 1)
mat[2:,1:]

# 2)
mat[3,4]

# 3)
mat[:3,1:2]

# 4) 
mat[-1,:] # -1 vai pegar a ultima linha

# 5) 
mat[3:,:]

In [ ]:
'''Metodos de NUmpy'''

# 1) Obter a soma de todos valores em "mat"
np.sum(mat)

# 2) obter o desvio padrão dos valores em "mat"
np.std(mat)

# 3) Obter a soma de todas as colunas em "mat"
mat.sum(axis=0)


# Biblioteca Pandas

É uma biblioteca de código fonte aberto escrita sobre o Numpy e é muito semelhante ao Excel 

In [10]:
import pandas as pd
import numpy as np
#series 
labels = ['a','b','c']
minha_lista = [10,20,30]
arr = np.array([10,20,30])
d = {'a':10, 'b':20, 'c':30}
#definindo a series (muito parecido com um dicionario)  
pd.Series(data=minha_lista, index=labels)


a    10
b    20
c    30
dtype: int64

In [9]:
series = pd.Series(data=minha_lista, index=labels)
#acessando o index 'b'
series['b']

20

In [11]:
#atribuindo o inverso 
pd.Series(labels, minha_lista)

10    a
20    b
30    c
dtype: object

In [12]:
#atribuindo usando 'arr' ao inves de 'minha_lista'
pd.Series(arr, labels)

a    10
b    20
c    30
dtype: int32

In [13]:
series1 = pd.Series([1,2,3,4], index=['EUA','Alemanha','URSS','Japão'])
series1

EUA         1
Alemanha    2
URSS        3
Japão       4
dtype: int64

In [16]:
series2 = pd.Series([1,2,3,4], index=['Alemanha','EUA','Itália','Japão'])
series2

Alemanha    1
EUA         2
Itália      3
Japão       4
dtype: int64

In [17]:
#OP. aritmeticas de series (vai realizar cada operação com base no indice)
series1 + series2
#Como URSS e Italia nao contem valores nas duas series por isso a saida e NaN


Alemanha    3.0
EUA         3.0
Itália      NaN
Japão       8.0
URSS        NaN
dtype: float64

In [2]:
#DataFrame
import pandas as pd
import numpy as np

#seed faz com que os numeros gerados seja iguais em qualquer computador
np.random.seed(101)
#definindo data frame (data, index)
df = pd.DataFrame(np.random.randn(5, 4), index='A B C D E'.split(), columns='W X Y Z'.split())
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [25]:
#pegar um dado desse dataframe (colunas)
df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [26]:
# as colunas sao series
type(df['W'])

pandas.core.series.Series

In [27]:
type(df)

pandas.core.frame.DataFrame

In [29]:
#pegando uma lista de colunas 
df[['W','Z']]

W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [34]:
# Criando novas colunas 
df['new'] = df['W'] + df['X']
df

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.334983
B  0.651118 -0.319318 -0.848077  0.605965  0.331800
C -2.018168  0.740122  0.528813 -0.589001 -1.278046
D  0.188695 -0.758872 -0.933237  0.955057 -0.570177
E  0.190794  1.978757  2.605967  0.683509  2.169552

In [35]:
# apagando colunas criada (precisa definir o eixo como 1 e o inplace altera diretamente o datframe)
df.drop('new', axis=1, inplace=True)
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [36]:
# localização de elementos por indice 
df.loc['A','W']

2.706849839399938

In [37]:
df.loc[['A','B'], ['X','Y','Z']]

X         Y         Z
A  0.628133  0.907969  0.503826
B -0.319318 -0.848077  0.605965

In [39]:
#segunda forma atraves de idices (posicao numerica)
df.iloc[1:4, 2:]

Y         Z
B -0.848077  0.605965
C  0.528813 -0.589001
D -0.933237  0.955057

In [41]:
#testes condicionais
bol = df >  0 #retorna um dataframe de true e false
df[bol] #NaN nos valores menores que zero (igual no numpy)


W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [42]:
#Neste caso a saida vai excluir a linha que em 'W' é menor que 0
df[df['W']>0] #exclui a linha C

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [44]:
#Os codigos sao equivalentes (Pegam os valores da coluna Y quando os valores da coluna W são maiores que 0)
df[df['W']>0]['Y']
#------------------
bol = df['W']>0
df2 = df[bol]
df2['Y']

A    0.907969
B   -0.848077
D   -0.933237
E    2.605967
Name: Y, dtype: float64

In [45]:
# Para essa comparação precisa do '&' ao inves do 'and' (para usar 'or' dev-se usar '|')
df[(df['W']>0) & (df['Y']>1)]

W         X         Y         Z
E  0.190794  1.978757  2.605967  0.683509

In [46]:
#resetar index
df.reset_index() #como nao tem o inplace = true para alterar o proprio data frame

index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

In [47]:
col = 'RS RJ SP AM SC'.split()
col

['RS', 'RJ', 'SP', 'AM', 'SC']

In [51]:
df['Estado'] = col
df

W         X         Y         Z Estado
estado                                               
RS      2.706850  0.628133  0.907969  0.503826     RS
RJ      0.651118 -0.319318 -0.848077  0.605965     RJ
SP     -2.018168  0.740122  0.528813 -0.589001     SP
AM      0.188695 -0.758872 -0.933237  0.955057     AM
SC      0.190794  1.978757  2.605967  0.683509     SC

In [52]:
#utilizando o metodo set_index para deixar os estados como index
df.set_index('Estado',inplace=True)
df

W         X         Y         Z
Estado                                        
RS      2.706850  0.628133  0.907969  0.503826
RJ      0.651118 -0.319318 -0.848077  0.605965
SP     -2.018168  0.740122  0.528813 -0.589001
AM      0.188695 -0.758872 -0.933237  0.955057
SC      0.190794  1.978757  2.605967  0.683509

In [53]:
# niveis de indice 
outside = ['G1', 'G1', 'G1', 'G2', 'G2', 'G2'] 
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside)) # cria uma lista de tuplas pelo metodo zip
hier_index = pd.MultiIndex.from_tuples(hier_index) # cria o indice multinivel

In [54]:
df = pd.DataFrame(np.random.randn(6,2), index=hier_index, columns=['A','B'])
df

A         B
G1 1  0.302665  1.693723
   2 -1.706086 -1.159119
   3 -0.134841  0.390528
G2 1  0.166905  0.184502
   2  0.807706  0.072960
   3  0.638787  0.329646

In [55]:
#acessando o indice multinivel
df.loc['G1']

A         B
1  0.302665  1.693723
2 -1.706086 -1.159119
3 -0.134841  0.390528

In [57]:
#definindo nome para os indices
df.index.names = ['Grupo', 'Numero']
df

A         B
Grupo Numero                    
G1    1       0.302665  1.693723
      2      -1.706086 -1.159119
      3      -0.134841  0.390528
G2    1       0.166905  0.184502
      2       0.807706  0.072960
      3       0.638787  0.329646

In [59]:
# Outra forma de selecionar dados em DataFrame de multinivel
df.xs(1, level='Numero') #pode selecionar elementos do nivel interno diretamente

A         B
Grupo                    
G1     0.302665  1.693723
G2     0.166905  0.184502

In [60]:
# Tratamento de dados ausentes 
d = {'A':[1,2,np.nan], 'B':[5,np.nan,np.nan], 'C':[1,2,3]}
d

{'A': [1, 2, nan], 'B': [5, nan, nan], 'C': [1, 2, 3]}

In [62]:
df = pd.DataFrame(d) # dataframe com valores faltantes
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [63]:
df.dropna(thresh=2) #exclui as linhas que contem 2 valores faltantes

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [65]:
df['A'].fillna(value=df['A'].mean()) # substitui os valores nulos por qualquer valor
# vai substituir o valor na da coluna A pela media dos outros dois valores

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

In [4]:
# GroupBy

data = {'Empresa':['GOOG', 'GOOG', 'MSFT', 'MSFT', 'FB', 'FB'],
        'Nome':['Sam','Charlie','Amy','Vanessa','Carl','Sarah'],
        'Venda':[200,120,340,124,243,350]}
df = pd.DataFrame(data)
df

Empresa     Nome  Venda
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [7]:
group = df.groupby('Empresa')
group

In [8]:
#pegando a soma das vendas por empresa
group.sum()

Nome  Venda
Empresa                   
FB        CarlSarah    593
GOOG     SamCharlie    320
MSFT     AmyVanessa    464

In [16]:
group.describe() # apresenta uma serie de metodos estaticos aplicados ao DataFrame

Venda                                                        
        count   mean         std    min     25%    50%     75%    max
Empresa                                                              
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [20]:
group = df.groupby('Nome')
group.sum().loc['Amy']

Empresa    MSFT
Venda       340
Name: Amy, dtype: object

In [21]:
import pandas as pd 
df1 = pd.DataFrame({ 'A': ['A0', 'A1', 'A2', 'A3'],
                    'B': ['B0', 'B1', 'B2', 'B3'],
                    'C': ['C0', 'C1', 'C2', 'C3'],
                    'D': ['D0', 'D1', 'D2', 'D3']},
                   index=[0,1,2,3])
df2 = pd.DataFrame({ 'A': ['A4', 'A5', 'A6', 'A7'],
                    'B': ['B4', 'B5', 'B6', 'B7'],
                    'C': ['C4', 'C5', 'C6', 'C7'],
                    'D': ['D4', 'D5', 'D6', 'D7']},
                   index=[4,5,6,7])
df3 = pd.DataFrame({ 'A': ['A8', 'A9', 'A10', 'A11'],
                    'B': ['B8', 'B9', 'B10', 'B11'],
                    'C': ['C8', 'C9', 'C10', 'C11'],
                    'D': ['D8', 'D9', 'D10', 'D11']},
                   index=[8,9,10,11])

In [22]:
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [23]:
df2

A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [24]:
df3

A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [25]:
# concatenação une dois DataFrames (de mesmo tamanho no eixo que for unir)
pd.concat([df1,df2,df3])

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [31]:
esquerda = pd.DataFrame({ 'key': ['K0', 'K1', 'K2', 'K3'],
                    'A': ['A0', 'A1', 'A2', 'A3'],
                    'B': ['B0', 'B1', 'B2', 'B3']})
direita = pd.DataFrame({ 'key': ['K0', 'K1', 'K2', 'K3'],
                    'C': ['C0', 'C1', 'C2', 'C3'],
                    'D': ['D0', 'D1', 'D2', 'D3']})

In [32]:
direita

key   C   D
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2
3  K3  C3  D3

In [33]:
esquerda

key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
3  K3  A3  B3

In [34]:
# permite unir dataframe que compartilham elementos em comum
pd.merge(esquerda,direita,how='inner',on='key')

key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

In [35]:
esquerda = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                    'B': ['B0', 'B1', 'B2']},
                        index=['K0', 'K1', 'K2'])
direita = pd.DataFrame({'C': ['C0', 'C2', 'C3'],
                    'D': ['D0', 'D2', 'D3']},
                        index=['K0', 'K2', 'K3'])

In [37]:
direita

C   D
K0  C0  D0
K2  C2  D2
K3  C3  D3

In [38]:
esquerda

A   B
K0  A0  B0
K1  A1  B1
K2  A2  B2

In [36]:
# junta e combina as colunas dos dataframes
# agrega o dataframe direita usando esquerda como referencia 
esquerda.join(direita) # os valores que o dataframe direita nao possui ficam como NaN

A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

In [39]:
esquerda.join(direita, how='outer') #pega todos os indices dos dois dataframes

A    B    C    D
K0   A0   B0   C0   D0
K1   A1   B1  NaN  NaN
K2   A2   B2   C2   D2
K3  NaN  NaN   C3   D3

In [48]:
df = pd.DataFrame({'col1':[1,2,3,4], 'col2':[444,555,666,444], 'col3':['abc','def','ghi','xyz']})
df.head()

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [41]:
#Metodo de seleção de dados unicos (colunas que possui unicos valores e nao copias)
df['col2'].unique() # semelhante ao metodo unique do numpy np.unique(df['col2'])

array([444, 555, 666], dtype=int64)

In [42]:
#tamanho da saida
df['col2'].nunique()

3

In [43]:
# une o metodo nunique e unique
df['col2'].value_counts() #quantidade de ocorrencia de cada valor

col2
444    2
555    1
666    1
Name: count, dtype: int64

In [45]:
#aplicar uma função a um data frame
def vezes2(x):
    return x*2

df['col1'].apply(vezes2) #apply aplica uma função para cada elemento do data frame

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [46]:
# usando apply e lambda 
df['col1'].apply(lambda x: x*x)

0     1
1     4
2     9
3    16
Name: col1, dtype: int64

In [47]:
# deletar colunas do data frame 
del df['col2']
df

col1 col3
0     1  abc
1     2  def
2     3  ghi
3     4  xyz

In [49]:
# ordenar data frame
df.sort_values(by='col2') # precisa definir inplace = true para aplicar as mudanças

col1  col2 col3
0     1   444  abc
3     4   444  xyz
1     2   555  def
2     3   666  ghi

In [55]:
df = pd.DataFrame({'col1':[1,2,3,np.nan], 
                   'col2':[np.nan,555,666,444], 
                   'col3':['abc','def','ghi','xyz']})
df.head()

col1   col2 col3
0   1.0    NaN  abc
1   2.0  555.0  def
2   3.0  666.0  ghi
3   NaN  444.0  xyz

In [53]:
# determina qual valor do data frame e nulo 
df.isnull()

col1   col2   col3
0  False   True  False
1  False  False  False
2  False  False  False
3   True  False  False

In [ ]:
# apaga valores NaN 
df.dropna()

In [56]:
#preenche valores nao nulos 
df['col1'].fillna(value=df['col1'].mean()) # inplace = true

0    1.0
1    2.0
2    3.0
3    2.0
Name: col1, dtype: float64

In [57]:
data = { 'A': ['foo', 'foo', 'foo', 'bar', 'bar', 'bar'],
                    'B': ['one', 'one', 'two', 'two', 'one', 'one'],
                    'C': ['x', 'y', 'x', 'y', 'x', 'y'],
                    'D': [1,3,2,5,4,1]}
df = pd.DataFrame(data)
df


A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

In [58]:
# reeordenando os dados
df.pivot_table(values='D',index=['A','B'], columns=['C']) #cria um indice multinivel

C          x    y
A   B            
bar one  4.0  1.0
    two  NaN  5.0
foo one  1.0  3.0
    two  2.0  NaN

In [66]:
# criar dataFrame a partir de um arquivo (pode ser em outrso formatos como sql ou html)
df = pd.read_csv('exemplo.csv',sep=',')
df

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [70]:
# se exemplo nao fosse csv poderia tranforma-lo em um .csv
df.to_csv('copiaexemplo.csv',sep=';',decimal=',')

In [78]:
# lendo de um html
df  = pd.read_html('https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/')

In [79]:
type(df)

list

In [80]:
len(df)

1

In [84]:
df[0]

Bank NameBank       CityCity StateSt  CertCert  \
0    Republic First Bank dba Republic Bank   Philadelphia      PA     27332   
1                            Citizens Bank       Sac City      IA      8758   
2                 Heartland Tri-State Bank        Elkhart      KS     25851   
3                      First Republic Bank  San Francisco      CA     59017   
4                           Signature Bank       New York      NY     57053   
..                                     ...            ...     ...       ...   
564                     Superior Bank, FSB       Hinsdale      IL     32646   
565                    Malta National Bank          Malta      OH      6629   
566        First Alliance Bank & Trust Co.     Manchester      NH     34264   
567      National State Bank of Metropolis     Metropolis      IL      3815   
568                       Bank of Honolulu       Honolulu      HI     21029   

                 Acquiring InstitutionAI Closing DateClosing  FundFund  
0      Fulton Bank, National Association      April 26, 2024     10546  
1              Iowa Trust & Savings Bank    November 3, 2023     10545  
2                 Dream First Bank, N.A.       July 28, 2023     10544  
3              JPMorgan Chase Bank, N.A.         May 1, 2023     10543  
4                    Flagstar Bank, N.A.      March 12, 2023     10540  
..                                   ...                 ...       ...  
564                Superior Federal, FSB       July 27, 2001      6004  
565                    North Valley Bank         May 3, 2001      4648  
566  Southern New Hampshire Bank & Trust    February 2, 2001      4647  
567              Banterra Bank of Marion   December 14, 2000      4646  
568                   Bank of the Orient    October 13, 2000      4645  

[569 rows x 7 columns]