Este arquivo contem todos os codigos vistos no card 4 e comentarios pessoais dos mesmos!

Card 4 tem por objetivo aprender duas bibliotecas de de python para data science e machine learning: 
**Numpy** e **Pandas**

# Biblioteca numpy 

é uma biblioteca de álgebra linear para python extremamente rapida, uma vez que seu principais metodos foram compilados em C

In [1]:
import numpy as np

In [3]:
minha_lista = [1,2,3]
minha_lista

np.array(minha_lista)

array([1, 2, 3])

In [4]:
minha_matriz = [[1,2,3],[4,5,6],[7,8,9]]
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
#cria um vetor de 0 a 9
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
#cria um vetor de 0 a 9 pulando de 2 em 2
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [8]:
#Vetor de zeros
arr = np.zeros(3)
arr

array([0., 0., 0.])

In [10]:
#Matriz de 0's
arr = np.zeros((5,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
#matriz de 1's
arr = np.ones((5,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
#matriz identidade
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
#Vai eixibir N numeros (n=2) igual mente espaçados dentro da serie ( no caso vai exibir 0 e 10)
np.linspace(0,10,2)

array([ 0., 10.])

In [18]:
#Sorteia N numeros (distribuição uniforme)
np.random.rand(5)


array([0.56206445, 0.07667343, 0.85228831, 0.75667539, 0.29114668])

In [17]:
#Sorteia numeros  (Distribuição normal)
np.random.randn(5)

array([-1.07941574,  0.0679575 ,  1.33579903, -0.88277932, -0.50737898])

In [19]:
#Sorteia numeros inteiros dentro de um intervalo (o a 99)
np.random.randint(0,100,10)

array([60, 18, 27, 78, 18, 32, 85, 38, 80, 85])

In [21]:
arr = np.random.rand(25)
#Tranforma o array em uma matriz 
arr.reshape((5,5))

array([[0.72234379, 0.59378909, 0.62207078, 0.88652403, 0.6365755 ],
       [0.66679841, 0.19814154, 0.43648384, 0.16573237, 0.00100407],
       [0.36653049, 0.79070726, 0.18491218, 0.19201502, 0.53403978],
       [0.44620221, 0.32036459, 0.06690853, 0.10161999, 0.77016261],
       [0.26964613, 0.19729457, 0.50996266, 0.93735167, 0.0312996 ]])

In [23]:
#Pega o maior valor de arr
arr.max()

0.9373516717018016

In [24]:
#Pega o maior valor de arr
arr.min()

0.0010040716758151769

In [25]:
#Indice do maior valor de arr 
arr.argmax()

23

In [28]:
#Indice do menor valor de arr 
arr.argmin()

9

In [31]:
array = np.arange(0,30,3)
array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [32]:
#elemento da pos 3 
array[3]

9

In [33]:
#elemento da pos 2 a 4 (se nao tiver nada no lugar do 2 começa da pos 0, 
#analogamente se nao tiver nada no lugar do 5 pega do primeiro valor de posição ( no caso 2) ate o final )
array[2:5]

array([ 6,  9, 12])

In [35]:
#a partir do indice 2 ate o final recebe o valor 100
array[2:] = 100
array


array([  0,   3, 100, 100, 100, 100, 100, 100, 100, 100])

In [37]:
array = np.arange(50).reshape((5,10))
array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [39]:
#primeiro colchete Linhas e segundo refere-se as colunas
#vai pegar as linhas ate a linha de indice 3
array[:3][:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [42]:
array2 = array[:3]
array2[:] = 100
#vai alterar tanto o array2 quanto o array original
#pois o array 2 vai apontar pro array original
array

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

In [47]:
#Agora realmente copia o array original
array2 = array[:3].copy()
array2[:] = 200
array


array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

In [48]:
#antes da virgula refere se as linhas e apos a virgula as colunas
#linhas de 1 a 3 e coluna de 5 em diante  
array[1:4,5:]

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [ 35,  36,  37,  38,  39]])

In [51]:
# Matriz de verdadeiros e falsos (verdadeiro onde é maior que 50)
array > 50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [52]:
array = np.arange(0,16)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [53]:
#soma 2 arrays de mesmo tamanho
array + array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [54]:
#subtrai 2 arrays de mesmo tamanho
array - array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [55]:
#multiplica 2 arrays de mesmo tamanho
array * array

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225])

In [57]:
#eleva o array ao quadrado 
array**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225])

In [58]:
#soma, subtração e multiplação de arrays por escalares
array + 100
array - 100
array * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000,
       1100, 1200, 1300, 1400, 1500])

In [59]:
#raiz quadrada elemento a elemento de um array 
np.sqrt(array)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335])

In [60]:
#exponenciação de um array 
np.exp(array)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06])

In [61]:
#media de um array 
np.mean(array)

7.5

In [62]:
#desvio padrao de um array
np.std(array)

4.6097722286464435

In [64]:
#seno dos elementos do vetor 
np.sin(array)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784])

In [66]:
#valor maximo do vetor de dois metodos
np.max(array)
array.max()

15

In [67]:
#valor minimo do vetor
np.min(array)
array.min()

0

**Exercícios sobre Numpy**

In [ ]:
# 1) crie uma mtriz de 10 zeros
np.zeros(10)

# 2) crie uma matriz de 10 ones
np.ones(10)

# 3) crie uma matriz de 10 cincos
np.ones(10)*5

# 4) crie um array de inteiros de 100 até 50 
np.arange(10,51)

# 5) crie um array de numeros pares de 10 ate 50 
np.arange(10,51,2)

# 6) crie uma matriz 3x3 com valores de 0 a 8
np.arange(0,9).reshape(3,3)

# 7) crie uma matriz identidade de 3x3
np.eye(3)

# 8) use numpy par gerar numeros aleatorios entre 0 e 1
np.random.rand(1)

# 9) use numpy para gerar um array de 25 numeros aleatorios tirados e uma distribuição normal
np.random.randn(25)

# 10) 
np.arange(0,101)/100

# 11) crie um array de tamanho 20 igualmente espaçado entre o e 1 
np.linspace(0,1,20)


In [ ]:
'''Indexação Numpy e seleção'''
mat = np.arange(1,26).reshape(5,5)

# 1)
mat[2:,1:]

# 2)
mat[3,4]

# 3)
mat[:3,1:2]

# 4) 
mat[-1,:] # -1 vai pegar a ultima linha

# 5) 
mat[3:,:]

In [ ]:
'''Metodos de NUmpy'''

# 1) Obter a soma de todos valores em "mat"
np.sum(mat)

# 2) obter o desvio padrão dos valores em "mat"
np.std(mat)

# 3) Obter a soma de todas as colunas em "mat"
mat.sum(axis=0)


# Biblioteca Pandas

É uma biblioteca de código fonte aberto escrita sobre o Numpy e é muito semelhante ao Excel 